spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=companydb
    username: sa
    password: admin123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
